"""
models.py — SQLAlchemy ORM Models for SecureCorrect
"""

import uuid
from datetime import datetime, timezone
from sqlalchemy import String, Integer, Text, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .database import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _new_uuid() -> str:
    return str(uuid.uuid4())


# ---------------------------------------------------------------------------
# User
# ---------------------------------------------------------------------------

class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_new_uuid)
    username: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)

    # Authentication hash generated by the client-side ECC engine (Argon2/SHA256).
    # If the user's password is recovered incorrectly on the client, this hash will not match.
    auth_hash: Mapped[str] = mapped_column(Text, nullable=False)

    # Reed-Solomon codeword generated by the client (hex-encoded string).
    ecc_codeword_hex: Mapped[str] = mapped_column(Text, nullable=False)

    # The 32-byte seed used by the client to generate the GF(256) mapping table (hex-encoded).
    mapping_seed_hex: Mapped[str] = mapped_column(String(64), nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)

    files: Mapped[list["File"]] = relationship("File", back_populates="owner",
                                                cascade="all, delete-orphan")


# ---------------------------------------------------------------------------
# File
# ---------------------------------------------------------------------------

class File(Base):
    __tablename__ = "files"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_new_uuid)
    user_id: Mapped[str] = mapped_column(String(36), ForeignKey("users.id"), nullable=False)

    # Original filename (as uploaded by the user)
    filename: Mapped[str] = mapped_column(String(512), nullable=False)

    # MIME type (detected on upload)
    mime_type: Mapped[str] = mapped_column(String(128), default="application/octet-stream")

    # Size in bytes of the *plaintext* file
    size_bytes: Mapped[int] = mapped_column(Integer, default=0)

    # Firebase Storage / S3 / Local object key (optional if using Google Drive)
    storage_key: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Google Drive File ID (for client-side cloud storage)
    google_file_id: Mapped[str | None] = mapped_column(String(128), nullable=True)

    # AES-GCM initialisation vector (hex-encoded, 16 bytes → 32 hex chars)
    iv_hex: Mapped[str] = mapped_column(String(32), nullable=False)

    # AES-GCM authentication tag (hex-encoded, 16 bytes → 32 hex chars)
    gcm_tag_hex: Mapped[str] = mapped_column(String(32), nullable=False)

    # HMAC-SHA256 of the plaintext (hex-encoded, 32 bytes → 64 hex chars)
    # This is the integrity guard: if decryption yields a different HMAC, access denied.
    hmac_hex: Mapped[str] = mapped_column(String(64), nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    owner: Mapped["User"] = relationship("User", back_populates="files")
